// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNBLT3p02EFyZ3XekGygwsVQLkZib5ng',
    appId: '1:298429508756:web:17cc1b811372a929d8d881',
    messagingSenderId: '298429508756',
    projectId: 'collegeapp-39706',
    authDomain: 'collegeapp-39706.firebaseapp.com',
    storageBucket: 'collegeapp-39706.appspot.com',
    measurementId: 'G-QBBK540T3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKBrbBQK6vEDUzdXJNER-EFKjNozZgun8',
    appId: '1:298429508756:android:9b9c5558dc77d257d8d881',
    messagingSenderId: '298429508756',
    projectId: 'collegeapp-39706',
    storageBucket: 'collegeapp-39706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZM7MxGnebPaiTGCjtclOGWz6-RTkCzug',
    appId: '1:298429508756:ios:06f5aff03cdb18bfd8d881',
    messagingSenderId: '298429508756',
    projectId: 'collegeapp-39706',
    storageBucket: 'collegeapp-39706.appspot.com',
    iosBundleId: 'com.example.collegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZM7MxGnebPaiTGCjtclOGWz6-RTkCzug',
    appId: '1:298429508756:ios:06f5aff03cdb18bfd8d881',
    messagingSenderId: '298429508756',
    projectId: 'collegeapp-39706',
    storageBucket: 'collegeapp-39706.appspot.com',
    iosBundleId: 'com.example.collegeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkNBLT3p02EFyZ3XekGygwsVQLkZib5ng',
    appId: '1:298429508756:web:000e25cd5e91db15d8d881',
    messagingSenderId: '298429508756',
    projectId: 'collegeapp-39706',
    authDomain: 'collegeapp-39706.firebaseapp.com',
    storageBucket: 'collegeapp-39706.appspot.com',
    measurementId: 'G-TBPGJ47WTR',
  );
}
