name: college_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  # google_fonts: ^6.2.0
  http: ^1.1.0
  lottie: ^2.3.0
  intl: ^0.17.0
  flutter_otp_text_field: ^1.1.3+2
  toastification: ^1.2.1
  slide_countdown: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/img/

  
    
